/**
 * Lucide icons: replaces [data-lucide] placeholders across the storefront.
 * Selective imports enabled for tree-shaking to reduce bundle size from ~365KB to ~20KB.
 */
import {
    createIcons,
    ArrowLeftRight,
    Banknote,
    Bell,
    CheckCheck,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsUp,
    CircleAlert,
    CircleCheck,
    CirclePlus,
    ClipboardList,
    Copy,
    CreditCard,
    Eye,
    Facebook,
    Funnel,
    Globe,
    Heart,
    Home,
    Instagram,
    KeyRound,
    Languages,
    LayoutGrid,
    Linkedin,
    List,
    LogIn,
    LogOut,
    Mail,
    Menu,
    MessageCircle,
    MessagesSquare,
    Mic,
    Minus,
    Package,
    Phone,
    Plus,
    Printer,
    ScanLine,
    Search,
    Send,
    Settings,
    Share2,
    ShoppingBag,
    ShoppingCart,
    SlidersHorizontal,
    Smartphone,
    Sparkles,
    Star,
    StarHalf,
    Tag,
    Trash2,
    Truck,
    Twitter,
    User,
    UserMinus,
    UserPlus,
    UserRound,
    X,
    Zap
} from 'lucide';

const icons = {
    ArrowLeftRight,
    Banknote,
    Bell,
    CheckCheck,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsUp,
    CircleAlert,
    CircleCheck,
    CirclePlus,
    ClipboardList,
    Copy,
    CreditCard,
    Eye,
    Facebook,
    Funnel,
    Globe,
    Heart,
    Home,
    Instagram,
    KeyRound,
    Languages,
    LayoutGrid,
    Linkedin,
    List,
    LogIn,
    LogOut,
    Mail,
    Menu,
    MessageCircle,
    MessagesSquare,
    Mic,
    Minus,
    Package,
    Phone,
    Plus,
    Printer,
    ScanLine,
    Search,
    Send,
    Settings,
    Share2,
    ShoppingBag,
    ShoppingCart,
    SlidersHorizontal,
    Smartphone,
    Sparkles,
    Star,
    StarHalf,
    Tag,
    Trash2,
    Truck,
    Twitter,
    User,
    UserMinus,
    UserPlus,
    UserRound,
    X,
    Zap
};

const kebabIcons = {
    'arrow-left-right': ArrowLeftRight,
    banknote: Banknote,
    bell: Bell,
    'check-check': CheckCheck,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'chevron-up': ChevronUp,
    'chevrons-up': ChevronsUp,
    'circle-alert': CircleAlert,
    'circle-check': CircleCheck,
    'circle-plus': CirclePlus,
    'clipboard-list': ClipboardList,
    copy: Copy,
    'credit-card': CreditCard,
    eye: Eye,
    facebook: Facebook,
    funnel: Funnel,
    globe: Globe,
    heart: Heart,
    home: Home,
    instagram: Instagram,
    'key-round': KeyRound,
    languages: Languages,
    'layout-grid': LayoutGrid,
    linkedin: Linkedin,
    list: List,
    'log-in': LogIn,
    'log-out': LogOut,
    mail: Mail,
    menu: Menu,
    'message-circle': MessageCircle,
    'messages-square': MessagesSquare,
    mic: Mic,
    minus: Minus,
    package: Package,
    phone: Phone,
    plus: Plus,
    printer: Printer,
    'scan-line': ScanLine,
    search: Search,
    send: Send,
    settings: Settings,
    'share-2': Share2,
    'shopping-bag': ShoppingBag,
    'shopping-cart': ShoppingCart,
    'sliders-horizontal': SlidersHorizontal,
    smartphone: Smartphone,
    sparkles: Sparkles,
    star: Star,
    'star-half': StarHalf,
    tag: Tag,
    'trash-2': Trash2,
    truck: Truck,
    twitter: Twitter,
    user: User,
    'user-minus': UserMinus,
    'user-plus': UserPlus,
    'user-round': UserRound,
    x: X,
    zap: Zap,
};


const BASE_ATTRS = {
    'stroke-width': 2,
    'stroke-linecap': 'round',
    'stroke-linejoin': 'round',
};

function runLucide(root) {
    if (typeof document === 'undefined') return;
    const scope = root && root.nodeType ? root : document;
    try {
        createIcons({
            icons: { ...icons, ...kebabIcons },
            attrs: BASE_ATTRS,
            root: scope,
        });
    } catch (e) {
        console.warn('[Stayl] Lucide createIcons failed', e);
    }
}

function init() {
    runLucide(document);
}

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init, { once: true });
} else {
    init();
}

window.refreshStaylLucide = function (root) {
    runLucide(root || document);
};

