<?php

/**
 * Default Bangladesh Thanas/Upazilas by District (English + Bengali).
 * Admin can edit and save to Frontend thana.list. Structure: [ 'DistrictEn' => [ ['en'=>'...','bn'=>'...'], ... ], ... ]
 */
return [
    'Dhaka' => [
        ['en' => 'Dhanmondi', 'bn' => 'ধানমন্ডি'],
        ['en' => 'Gulshan', 'bn' => 'গুলশান'],
        ['en' => 'Motijheel', 'bn' => 'মতিঝিল'],
        ['en' => 'Mirpur', 'bn' => 'মিরপুর'],
        ['en' => 'Uttara', 'bn' => 'উত্তরা'],
        ['en' => 'Banani', 'bn' => 'বনানী'],
        ['en' => 'Mohakhali', 'bn' => 'মহাখালী'],
        ['en' => 'Ramna', 'bn' => 'রমনা'],
        ['en' => 'Lalbagh', 'bn' => 'লালবাগ'],
        ['en' => 'Cantonment', 'bn' => 'ক্যান্টনমেন্ট'],
        ['en' => 'Tejgaon', 'bn' => 'তেজগাঁও'],
        ['en' => 'Sabujbagh', 'bn' => 'সবুজবাগ'],
        ['en' => 'Demra', 'bn' => 'ডেমরা'],
        ['en' => 'Shyampur', 'bn' => 'শ্যামপুর'],
        ['en' => 'Kamrangirchar', 'bn' => 'কামরাঙ্গীচর'],
        ['en' => 'Dhaka Cantonment', 'bn' => 'ঢাকা ক্যান্টনমেন্ট'],
        ['en' => 'Badda', 'bn' => 'বাড্ডা'],
        ['en' => 'Khilgaon', 'bn' => 'খিলগাঁও'],
        ['en' => 'Pallabi', 'bn' => 'পল্লবী'],
        ['en' => 'Kafrul', 'bn' => 'কাফরুল'],
        ['en' => 'Savar', 'bn' => 'সাভার'],
        ['en' => 'Dhamrai', 'bn' => 'ধামরাই'],
        ['en' => 'Dohar', 'bn' => 'দোহার'],
        ['en' => 'Keraniganj', 'bn' => 'কেরানীগঞ্জ'],
        ['en' => 'Nawabganj', 'bn' => 'নবাবগঞ্জ'],
    ],
    'Gazipur' => [
        ['en' => 'Gazipur Sadar', 'bn' => 'গাজীপুর সদর'],
        ['en' => 'Kaliakair', 'bn' => 'কালিয়াকৈর'],
        ['en' => 'Kapasia', 'bn' => 'কাপাসিয়া'],
        ['en' => 'Sreepur', 'bn' => 'শ্রীপুর'],
        ['en' => 'Kaliganj', 'bn' => 'কালীগঞ্জ'],
    ],
    'Narayanganj' => [
        ['en' => 'Narayanganj Sadar', 'bn' => 'নারায়ণগঞ্জ সদর'],
        ['en' => 'Sonargaon', 'bn' => 'সোনারগাঁও'],
        ['en' => 'Bandar', 'bn' => 'বন্দর'],
        ['en' => 'Araihazar', 'bn' => 'আড়াইহাজার'],
        ['en' => 'Rupganj', 'bn' => 'রূপগঞ্জ'],
    ],
    'Tangail' => [
        ['en' => 'Tangail Sadar', 'bn' => 'টাঙ্গাইল সদর'],
        ['en' => 'Gopalpur', 'bn' => 'গোপালপুর'],
        ['en' => 'Basail', 'bn' => 'বাসাইল'],
        ['en' => 'Bhuapur', 'bn' => 'ভুয়াপুর'],
        ['en' => 'Delduar', 'bn' => 'দেলদুয়ার'],
        ['en' => 'Ghatail', 'bn' => 'ঘাটাইল'],
        ['en' => 'Kalihati', 'bn' => 'কালিহাতী'],
        ['en' => 'Madhupur', 'bn' => 'মধুপুর'],
        ['en' => 'Mirzapur', 'bn' => 'মির্জাপুর'],
        ['en' => 'Nagarpur', 'bn' => 'নাগরপুর'],
        ['en' => 'Sakhipur', 'bn' => 'সখীপুর'],
    ],
    'Chittagong' => [
        ['en' => 'Anwara', 'bn' => 'আনোয়ারা'],
        ['en' => 'Banshkhali', 'bn' => 'বাঁশখালী'],
        ['en' => 'Boalkhali', 'bn' => 'বোয়ালখালী'],
        ['en' => 'Chandanaish', 'bn' => 'চন্দনাইশ'],
        ['en' => 'Chandgaon', 'bn' => 'চাঁদগাঁও'],
        ['en' => 'Chittagong Port', 'bn' => 'চট্টগ্রাম বন্দর'],
        ['en' => 'Double Mooring', 'bn' => 'ডবল মুরিং'],
        ['en' => 'Fatikchhari', 'bn' => 'ফটিকছড়ি'],
        ['en' => 'Hathazari', 'bn' => 'হাটহাজারী'],
        ['en' => 'Karnaphuli', 'bn' => 'কর্ণফুলী'],
        ['en' => 'Kotwali', 'bn' => 'কোতোয়ালী'],
        ['en' => 'Lohagara', 'bn' => 'লোহাগাড়া'],
        ['en' => 'Mirsharai', 'bn' => 'মীরসরাই'],
        ['en' => 'Pahartali', 'bn' => 'পাহাড়তলী'],
        ['en' => 'Panchlaish', 'bn' => 'পাঁচলাইশ'],
        ['en' => 'Patiya', 'bn' => 'পটিয়া'],
        ['en' => 'Rangunia', 'bn' => 'রাঙ্গুনিয়া'],
        ['en' => 'Raozan', 'bn' => 'রাউজান'],
        ['en' => 'Sandwip', 'bn' => 'সন্দ্বীপ'],
        ['en' => 'Satkania', 'bn' => 'সাতকানিয়া'],
        ['en' => 'Sitakunda', 'bn' => 'সীতাকুণ্ড'],
        ['en' => 'Halishahar', 'bn' => 'হালিশহর'],
        ['en' => 'Bayezid', 'bn' => 'বায়েজিদ'],
    ],
    'Cox\'s Bazar' => [
        ['en' => 'Cox\'s Bazar Sadar', 'bn' => 'কক্সবাজার সদর'],
        ['en' => 'Chakaria', 'bn' => 'চকরিয়া'],
        ['en' => 'Kutubdia', 'bn' => 'কুতুবদিয়া'],
        ['en' => 'Maheshkhali', 'bn' => 'মহেশখালী'],
        ['en' => 'Ramu', 'bn' => 'রামু'],
        ['en' => 'Teknaf', 'bn' => 'টেকনাফ'],
        ['en' => 'Ukhia', 'bn' => 'উখিয়া'],
        ['en' => 'Pekua', 'bn' => 'পেকুয়া'],
        ['en' => 'Eidgaon', 'bn' => 'ঈদগাঁও'],
    ],
    'Comilla' => [
        ['en' => 'Comilla Adarsha Sadar', 'bn' => 'কুমিল্লা আদর্শ সদর'],
        ['en' => 'Comilla Sadar Dakshin', 'bn' => 'কুমিল্লা সদর দক্ষিণ'],
        ['en' => 'Barura', 'bn' => 'বরুড়া'],
        ['en' => 'Brahmanpara', 'bn' => 'ব্রাহ্মণপাড়া'],
        ['en' => 'Burichang', 'bn' => 'বুড়িচং'],
        ['en' => 'Chandina', 'bn' => 'চান্দিনা'],
        ['en' => 'Chauddagram', 'bn' => 'চৌদ্দগ্রাম'],
        ['en' => 'Daudkandi', 'bn' => 'দাউদকান্দি'],
        ['en' => 'Debidwar', 'bn' => 'দেবিদ্বার'],
        ['en' => 'Homna', 'bn' => 'হোমনা'],
        ['en' => 'Laksam', 'bn' => 'লাকসাম'],
        ['en' => 'Lalmai', 'bn' => 'লালমাই'],
        ['en' => 'Monohargonj', 'bn' => 'মনোহরগঞ্জ'],
        ['en' => 'Meghna', 'bn' => 'মেঘনা'],
        ['en' => 'Muradnagar', 'bn' => 'মুরাদনগর'],
        ['en' => 'Nangalkot', 'bn' => 'নাঙ্গলকোট'],
        ['en' => 'Titas', 'bn' => 'তিতাস'],
    ],
    'Sylhet' => [
        ['en' => 'Sylhet Sadar', 'bn' => 'সিলেট সদর'],
        ['en' => 'Beanibazar', 'bn' => 'বিয়ানীবাজার'],
        ['en' => 'Bishwanath', 'bn' => 'বিশ্বনাথ'],
        ['en' => 'Companiganj', 'bn' => 'কোম্পানীগঞ্জ'],
        ['en' => 'Dakshin Surma', 'bn' => 'দক্ষিণ সুরমা'],
        ['en' => 'Fenchuganj', 'bn' => 'ফেঞ্চুগঞ্জ'],
        ['en' => 'Golapganj', 'bn' => 'গোলাপগঞ্জ'],
        ['en' => 'Gowainghat', 'bn' => 'গোয়াইনঘাট'],
        ['en' => 'Jaintiapur', 'bn' => 'জৈন্তাপুর'],
        ['en' => 'Kanaighat', 'bn' => 'কানাইঘাট'],
        ['en' => 'Osmani Nagar', 'bn' => 'ওসমানী নগর'],
        ['en' => 'Zakiganj', 'bn' => 'জকিগঞ্জ'],
    ],
    'Rajshahi' => [
        ['en' => 'Rajshahi Sadar', 'bn' => 'রাজশাহী সদর'],
        ['en' => 'Bagha', 'bn' => 'বাঘা'],
        ['en' => 'Bagmara', 'bn' => 'বাগমারা'],
        ['en' => 'Charghat', 'bn' => 'চারঘাট'],
        ['en' => 'Durgapur', 'bn' => 'দুর্গাপুর'],
        ['en' => 'Godagari', 'bn' => 'গোদাগাড়ী'],
        ['en' => 'Mohanpur', 'bn' => 'মোহনপুর'],
        ['en' => 'Paba', 'bn' => 'পবা'],
        ['en' => 'Puthia', 'bn' => 'পুঠিয়া'],
        ['en' => 'Tanore', 'bn' => 'তানোর'],
    ],
    'Khulna' => [
        ['en' => 'Khulna Sadar', 'bn' => 'খুলনা সদর'],
        ['en' => 'Batiaghata', 'bn' => 'বটিয়াঘাটা'],
        ['en' => 'Dacope', 'bn' => 'দাকোপ'],
        ['en' => 'Dumuria', 'bn' => 'দুমুরিয়া'],
        ['en' => 'Dighalia', 'bn' => 'দিঘলিয়া'],
        ['en' => 'Koyra', 'bn' => 'কয়রা'],
        ['en' => 'Paikgachha', 'bn' => 'পাইকগাছা'],
        ['en' => 'Phultala', 'bn' => 'ফুলতলা'],
        ['en' => 'Rupsa', 'bn' => 'রূপসা'],
        ['en' => 'Terokhada', 'bn' => 'তেরখাদা'],
    ],
    'Barisal' => [
        ['en' => 'Barisal Sadar', 'bn' => 'বরিশাল সদর'],
        ['en' => 'Agailjhara', 'bn' => 'আগৈলঝারা'],
        ['en' => 'Babuganj', 'bn' => 'বাবুগঞ্জ'],
        ['en' => 'Bakerganj', 'bn' => 'বাকেরগঞ্জ'],
        ['en' => 'Banaripara', 'bn' => 'বানারীপাড়া'],
        ['en' => 'Gaurnadi', 'bn' => 'গৌরনদী'],
        ['en' => 'Hizla', 'bn' => 'হিজলা'],
        ['en' => 'Mehendiganj', 'bn' => 'মেহেন্দিগঞ্জ'],
        ['en' => 'Muladi', 'bn' => 'মুলাদী'],
        ['en' => 'Wazirpur', 'bn' => 'ওয়াজিরপুর'],
    ],
    'Rangpur' => [
        ['en' => 'Rangpur Sadar', 'bn' => 'রংপুর সদর'],
        ['en' => 'Badarganj', 'bn' => 'বদরগঞ্জ'],
        ['en' => 'Gangachara', 'bn' => 'গঙ্গাচড়া'],
        ['en' => 'Kaunia', 'bn' => 'কাউনিয়া'],
        ['en' => 'Mithapukur', 'bn' => 'মিঠাপুকুর'],
        ['en' => 'Pirgachha', 'bn' => 'পীরগাছা'],
        ['en' => 'Pirganj', 'bn' => 'পীরগঞ্জ'],
        ['en' => 'Taraganj', 'bn' => 'তারাগঞ্জ'],
    ],
    'Mymensingh' => [
        ['en' => 'Mymensingh Sadar', 'bn' => 'ময়মনসিংহ সদর'],
        ['en' => 'Bhaluka', 'bn' => 'ভালুকা'],
        ['en' => 'Dhobaura', 'bn' => 'ধোবাউড়া'],
        ['en' => 'Fulbaria', 'bn' => 'ফুলবাড়িয়া'],
        ['en' => 'Gafargaon', 'bn' => 'গফরগাঁও'],
        ['en' => 'Gauripur', 'bn' => 'গৌরীপুর'],
        ['en' => 'Haluaghat', 'bn' => 'হালুয়াঘাট'],
        ['en' => 'Ishwarganj', 'bn' => 'ঈশ্বরগঞ্জ'],
        ['en' => 'Muktagachha', 'bn' => 'মুক্তাগাছা'],
        ['en' => 'Nandail', 'bn' => 'নন্দাইল'],
        ['en' => 'Phulpur', 'bn' => 'ফুলপুর'],
        ['en' => 'Tara Khanda', 'bn' => 'তারাকান্দা'],
        ['en' => 'Trishal', 'bn' => 'ত্রিশাল'],
    ],
    'Bogra' => [
        ['en' => 'Bogra Sadar', 'bn' => 'বগুড়া সদর'],
        ['en' => 'Adamdighi', 'bn' => 'আদমদিঘি'],
        ['en' => 'Dhunat', 'bn' => 'ধুনট'],
        ['en' => 'Dhupchanchia', 'bn' => 'ধুপচাঁচিয়া'],
        ['en' => 'Gabtali', 'bn' => 'গাবতলী'],
        ['en' => 'Kahaloo', 'bn' => 'কাহালু'],
        ['en' => 'Nandigram', 'bn' => 'নন্দীগ্রাম'],
        ['en' => 'Sariakandi', 'bn' => 'সারিয়াকান্দি'],
        ['en' => 'Shajahanpur', 'bn' => 'শাজাহানপুর'],
        ['en' => 'Sherpur', 'bn' => 'শেরপুর'],
        ['en' => 'Shibganj', 'bn' => 'শিবগঞ্জ'],
        ['en' => 'Sonatola', 'bn' => 'সোনাতলা'],
    ],
    'Jessore' => [
        ['en' => 'Jessore Sadar', 'bn' => 'যশোর সদর'],
        ['en' => 'Abhaynagar', 'bn' => 'অভয়নগর'],
        ['en' => 'Bagherpara', 'bn' => 'বাঘারপাড়া'],
        ['en' => 'Chaugachha', 'bn' => 'চৌগাছা'],
        ['en' => 'Jhikargachha', 'bn' => 'ঝিকরগাছা'],
        ['en' => 'Keshabpur', 'bn' => 'কেশবপুর'],
        ['en' => 'Manirampur', 'bn' => 'মণিরামপুর'],
        ['en' => 'Sharsha', 'bn' => 'শার্শা'],
    ],
    'Dinajpur' => [
        ['en' => 'Dinajpur Sadar', 'bn' => 'দিনাজপুর সদর'],
        ['en' => 'Birampur', 'bn' => 'বিরামপুর'],
        ['en' => 'Birganj', 'bn' => 'বীরগঞ্জ'],
        ['en' => 'Biral', 'bn' => 'বিরল'],
        ['en' => 'Bochaganj', 'bn' => 'বোচাগঞ্জ'],
        ['en' => 'Chirirbandar', 'bn' => 'চিরিরবন্দর'],
        ['en' => 'Phulbari', 'bn' => 'ফুলবাড়ী'],
        ['en' => 'Ghoraghat', 'bn' => 'ঘোড়াঘাট'],
        ['en' => 'Hakimpur', 'bn' => 'হাকিমপুর'],
        ['en' => 'Kaharole', 'bn' => 'কাহারোল'],
        ['en' => 'Khansama', 'bn' => 'খানসামা'],
        ['en' => 'Nawabganj', 'bn' => 'নবাবগঞ্জ'],
        ['en' => 'Parbatipur', 'bn' => 'পার্বতীপুর'],
    ],
    // Remaining 48 districts: at least Sadar + key upazilas (EN + BN). Run seeder to populate all 64.
    'Barguna' => [['en' => 'Barguna Sadar', 'bn' => 'বরগুনা সদর'], ['en' => 'Amtali', 'bn' => 'আমতলী'], ['en' => 'Bamna', 'bn' => 'বামনা'], ['en' => 'Betagi', 'bn' => 'বেতাগী'], ['en' => 'Patharghata', 'bn' => 'পাথরঘাটা'], ['en' => 'Taltali', 'bn' => 'তালতলী']],
    'Bhola' => [['en' => 'Bhola Sadar', 'bn' => 'ভোলা সদর'], ['en' => 'Burhanuddin', 'bn' => 'বুরহানউদ্দিন'], ['en' => 'Char Fasson', 'bn' => 'চর ফ্যাশন'], ['en' => 'Daulatkhan', 'bn' => 'দৌলতখান'], ['en' => 'Lalmohan', 'bn' => 'লালমোহন'], ['en' => 'Manpura', 'bn' => 'মনপুরা'], ['en' => 'Tazumuddin', 'bn' => 'তজুমদ্দিন']],
    'Jhalokati' => [['en' => 'Jhalokati Sadar', 'bn' => 'ঝালকাঠি সদর'], ['en' => 'Kathalia', 'bn' => 'কাঠালিয়া'], ['en' => 'Nalchity', 'bn' => 'নলছিটি'], ['en' => 'Rajapur', 'bn' => 'রাজাপুর']],
    'Patuakhali' => [['en' => 'Patuakhali Sadar', 'bn' => 'পটুয়াখালী সদর'], ['en' => 'Bauphal', 'bn' => 'বাউফল'], ['en' => 'Dashmina', 'bn' => 'দশমিনা'], ['en' => 'Galachipa', 'bn' => 'গলাচিপা'], ['en' => 'Kalapara', 'bn' => 'কলাপাড়া'], ['en' => 'Mirzaganj', 'bn' => 'মির্জাগঞ্জ'], ['en' => 'Rangabali', 'bn' => 'রাঙ্গাবালী'], ['en' => 'Dumki', 'bn' => 'দুমকি']],
    'Pirojpur' => [['en' => 'Pirojpur Sadar', 'bn' => 'পিরোজপুর সদর'], ['en' => 'Bhandaria', 'bn' => 'ভান্ডারিয়া'], ['en' => 'Kawkhali', 'bn' => 'কাউখালী'], ['en' => 'Mathbaria', 'bn' => 'মঠবাড়িয়া'], ['en' => 'Nazirpur', 'bn' => 'নাজিরপুর'], ['en' => 'Nesarabad (Swarupkati)', 'bn' => 'নেছারাবাদ (স্বরূপকাঠী)'], ['en' => 'Indurkani', 'bn' => 'ইন্দুরকানী']],
    'Bandarban' => [['en' => 'Bandarban Sadar', 'bn' => 'বান্দরবান সদর'], ['en' => 'Ali Kadam', 'bn' => 'আলীকদম'], ['en' => 'Lama', 'bn' => 'লামা'], ['en' => 'Naikhongchhari', 'bn' => 'নাইক্ষ্যংছড়ি'], ['en' => 'Rowangchhari', 'bn' => 'রোয়াংছড়ি'], ['en' => 'Ruma', 'bn' => 'রুমা'], ['en' => 'Thanchi', 'bn' => 'থানচি']],
    'Brahmanbaria' => [['en' => 'Brahmanbaria Sadar', 'bn' => 'ব্রাহ্মণবাড়িয়া সদর'], ['en' => 'Akhaura', 'bn' => 'আখাউড়া'], ['en' => 'Bancharampur', 'bn' => 'বাঞ্ছারামপুর'], ['en' => 'Kasba', 'bn' => 'কসবা'], ['en' => 'Nabinagar', 'bn' => 'নবীনগর'], ['en' => 'Nasirnagar', 'bn' => 'নাসিরনগর'], ['en' => 'Sarail', 'bn' => 'সরাইল'], ['en' => 'Ashuganj', 'bn' => 'আশুগঞ্জ'], ['en' => 'Bijoynagar', 'bn' => 'বিজয়নগর']],
    'Chandpur' => [['en' => 'Chandpur Sadar', 'bn' => 'চাঁদপুর সদর'], ['en' => 'Faridganj', 'bn' => 'ফরিদগঞ্জ'], ['en' => 'Haimchar', 'bn' => 'হাইমচর'], ['en' => 'Haziganj', 'bn' => 'হাজীগঞ্জ'], ['en' => 'Kachua', 'bn' => 'কচুয়া'], ['en' => 'Matlab Dakshin', 'bn' => 'মতলব দক্ষিণ'], ['en' => 'Matlab Uttar', 'bn' => 'মতলব উত্তর'], ['en' => 'Shahrasti', 'bn' => 'শাহরাস্তি']],
    'Feni' => [['en' => 'Feni Sadar', 'bn' => 'ফেনী সদর'], ['en' => 'Chhagalnaiya', 'bn' => 'ছাগলনাইয়া'], ['en' => 'Daganbhuiyan', 'bn' => 'দাগনভূঁইয়া'], ['en' => 'Parshuram', 'bn' => 'পরশুরাম'], ['en' => 'Sonagazi', 'bn' => 'সোনাগাজী'], ['en' => 'Fulgazi', 'bn' => 'ফুলগাজী']],
    'Khagrachhari' => [['en' => 'Khagrachhari', 'bn' => 'খাগড়াছড়ি'], ['en' => 'Dighinala', 'bn' => 'দিঘীনালা'], ['en' => 'Lakshmichhari', 'bn' => 'লক্ষ্মীছড়ি'], ['en' => 'Mahalchhari', 'bn' => 'মহালছড়ি'], ['en' => 'Manikchhari', 'bn' => 'মানিকছড়ি'], ['en' => 'Matiranga', 'bn' => 'মাটিরাঙ্গা'], ['en' => 'Panchhari', 'bn' => 'পানছড়ি'], ['en' => 'Ramgarh', 'bn' => 'রামগড়'], ['en' => 'Guimara', 'bn' => 'গুইমারা']],
    'Lakshmipur' => [['en' => 'Lakshmipur Sadar', 'bn' => 'লক্ষ্মীপুর সদর'], ['en' => 'Raipur', 'bn' => 'রায়পুর'], ['en' => 'Ramganj', 'bn' => 'রামগঞ্জ'], ['en' => 'Ramgati', 'bn' => 'রামগতি'], ['en' => 'Kamalnagar', 'bn' => 'কমলনগর']],
    'Noakhali' => [['en' => 'Noakhali Sadar', 'bn' => 'নোয়াখালী সদর'], ['en' => 'Begumganj', 'bn' => 'বেগমগঞ্জ'], ['en' => 'Chatkhil', 'bn' => 'চাটখিল'], ['en' => 'Companiganj', 'bn' => 'কোম্পানীগঞ্জ'], ['en' => 'Hatiya', 'bn' => 'হাতিয়া'], ['en' => 'Senbagh', 'bn' => 'সেনবাগ'], ['en' => 'Sonaimuri', 'bn' => 'সোনাইমুড়ী'], ['en' => 'Subarnachar', 'bn' => 'সুবর্ণচর'], ['en' => 'Kabirhat', 'bn' => 'কবিরহাট']],
    'Rangamati' => [['en' => 'Rangamati Sadar', 'bn' => 'রাঙ্গামাটি সদর'], ['en' => 'Bagaichhari', 'bn' => 'বাঘাইছড়ি'], ['en' => 'Barkal', 'bn' => 'বরকল'], ['en' => 'Belaichhari', 'bn' => 'বেলাইছড়ি'], ['en' => 'Juraichhari', 'bn' => 'জুরাইছড়ি'], ['en' => 'Kaptai', 'bn' => 'কাপ্তাই'], ['en' => 'Kawkhali (Betbunia)', 'bn' => 'কাউখালী (বেতবুনিয়া)'], ['en' => 'Langadu', 'bn' => 'লংগদু'], ['en' => 'Naniyachar', 'bn' => 'নানিয়াচর'], ['en' => 'Rajasthali', 'bn' => 'রাজস্থলী']],
    'Faridpur' => [['en' => 'Faridpur Sadar', 'bn' => 'ফরিদপুর সদর'], ['en' => 'Alfadanga', 'bn' => 'আলফাডাঙ্গা'], ['en' => 'Bhanga', 'bn' => 'ভাঙ্গা'], ['en' => 'Boalmari', 'bn' => 'বোয়ালমারী'], ['en' => 'Charbhadrasan', 'bn' => 'চরভদ্রাসন'], ['en' => 'Madhukhali', 'bn' => 'মধুখালী'], ['en' => 'Nagarkanda', 'bn' => 'নগরকান্দা'], ['en' => 'Sadarpur', 'bn' => 'সদরপুর'], ['en' => 'Saltha', 'bn' => 'সালথা']],
    'Gopalganj' => [['en' => 'Gopalganj Sadar', 'bn' => 'গোপালগঞ্জ সদর'], ['en' => 'Kashiani', 'bn' => 'কাশিয়ানী'], ['en' => 'Kotalipara', 'bn' => 'কোটালীপাড়া'], ['en' => 'Muksudpur', 'bn' => 'মুকসুদপুর'], ['en' => 'Tungipara', 'bn' => 'টুংগীপাড়া']],
    'Kishoreganj' => [['en' => 'Kishoreganj Sadar', 'bn' => 'কিশোরগঞ্জ সদর'], ['en' => 'Austagram', 'bn' => 'অষ্টগ্রাম'], ['en' => 'Bajitpur', 'bn' => 'বাজিতপুর'], ['en' => 'Bhairab', 'bn' => 'ভৈরব'], ['en' => 'Hossainpur', 'bn' => 'হোসেনপুর'], ['en' => 'Itna', 'bn' => 'ইটনা'], ['en' => 'Karimganj', 'bn' => 'করিমগঞ্জ'], ['en' => 'Katiadi', 'bn' => 'কটিয়াদী'], ['en' => 'Kuliarchar', 'bn' => 'কুলিয়ারচর'], ['en' => 'Mithamain', 'bn' => 'মিঠামইন'], ['en' => 'Nikli', 'bn' => 'নিকলী'], ['en' => 'Pakundia', 'bn' => 'পাকুন্দিয়া'], ['en' => 'Tarail', 'bn' => 'তাড়াইল']],
    'Madaripur' => [['en' => 'Madaripur Sadar', 'bn' => 'মাদারীপুর সদর'], ['en' => 'Dasar', 'bn' => 'ডাসার'], ['en' => 'Kalkini', 'bn' => 'কালকিনি'], ['en' => 'Rajoir', 'bn' => 'রাজৈর'], ['en' => 'Shibchar', 'bn' => 'শিবচর']],
    'Manikganj' => [['en' => 'Manikganj Sadar', 'bn' => 'মানিকগঞ্জ সদর'], ['en' => 'Daulatpur', 'bn' => 'দৌলতপুর'], ['en' => 'Ghior', 'bn' => 'ঘিওর'], ['en' => 'Harirampur', 'bn' => 'হরিরামপুর'], ['en' => 'Saturia', 'bn' => 'সাটুরিয়া'], ['en' => 'Shibalaya', 'bn' => 'শিবালয়'], ['en' => 'Singair', 'bn' => 'সিংগাইর']],
    'Munshiganj' => [['en' => 'Munshiganj Sadar', 'bn' => 'মুন্সিগঞ্জ সদর'], ['en' => 'Gazaria', 'bn' => 'গজারিয়া'], ['en' => 'Lohajang', 'bn' => 'লৌহজং'], ['en' => 'Sirajdikhan', 'bn' => 'সিরাজদিখান'], ['en' => 'Sreenagar', 'bn' => 'শ্রীনগর'], ['en' => 'Tongibari', 'bn' => 'টংগিবাড়ী']],
    'Narsingdi' => [['en' => 'Narsingdi Sadar', 'bn' => 'নরসিংদী সদর'], ['en' => 'Belabo', 'bn' => 'বেলাবো'], ['en' => 'Monohardi', 'bn' => 'মনোহরদী'], ['en' => 'Palash', 'bn' => 'পলাশ'], ['en' => 'Raipura', 'bn' => 'রায়পুরা'], ['en' => 'Shibpur', 'bn' => 'শিবপুর']],
    'Rajbari' => [['en' => 'Rajbari Sadar', 'bn' => 'রাজবাড়ী সদর'], ['en' => 'Baliakandi', 'bn' => 'বালিয়াকান্দি'], ['en' => 'Goalandaghat', 'bn' => 'গোয়ালন্দ ঘাট'], ['en' => 'Pangsha', 'bn' => 'পাংশা'], ['en' => 'Kalukhali', 'bn' => 'কালুখালী']],
    'Shariatpur' => [['en' => 'Shariatpur Sadar', 'bn' => 'শরীয়তপুর সদর'], ['en' => 'Bhedarganj', 'bn' => 'ভেদরগঞ্জ'], ['en' => 'Damudya', 'bn' => 'দামুদিয়া'], ['en' => 'Gosairhat', 'bn' => 'গোসাইরহাট'], ['en' => 'Naria', 'bn' => 'নড়িয়া'], ['en' => 'Zajira', 'bn' => 'জাজিরা']],
    'Bagerhat' => [['en' => 'Bagerhat Sadar', 'bn' => 'বাগেরহাট সদর'], ['en' => 'Chitalmari', 'bn' => 'চিতলমারী'], ['en' => 'Fakirhat', 'bn' => 'ফকিরহাট'], ['en' => 'Kachua', 'bn' => 'কচুয়া'], ['en' => 'Mollahat', 'bn' => 'মোল্লাহাট'], ['en' => 'Mongla', 'bn' => 'মোংলা'], ['en' => 'Morrelganj', 'bn' => 'মোরেলগঞ্জ'], ['en' => 'Rampal', 'bn' => 'রামপাল'], ['en' => 'Sarankhola', 'bn' => 'শরণখোলা']],
    'Chuadanga' => [['en' => 'Chuadanga Sadar', 'bn' => 'চুয়াডাঙ্গা সদর'], ['en' => 'Alamdanga', 'bn' => 'আলমডাঙ্গা'], ['en' => 'Damurhuda', 'bn' => 'দামুড়হুদা'], ['en' => 'Jibannagar', 'bn' => 'জীবননগর']],
    'Jhenaidah' => [['en' => 'Jhenaidah Sadar', 'bn' => 'ঝিনাইদহ সদর'], ['en' => 'Harinakunda', 'bn' => 'হরিণাকুণ্ডু'], ['en' => 'Kaliganj', 'bn' => 'কালীগঞ্জ'], ['en' => 'Kotchandpur', 'bn' => 'কোটচাঁদপুর'], ['en' => 'Maheshpur', 'bn' => 'মহেশপুর'], ['en' => 'Shailkupa', 'bn' => 'শৈলকুপা']],
    'Kushtia' => [['en' => 'Kushtia Sadar', 'bn' => 'কুষ্টিয়া সদর'], ['en' => 'Bheramara', 'bn' => 'ভেড়ামারা'], ['en' => 'Daulatpur', 'bn' => 'দৌলতপুর'], ['en' => 'Khoksa', 'bn' => 'খোকসা'], ['en' => 'Kumarkhali', 'bn' => 'কুমারখালী'], ['en' => 'Mirpur', 'bn' => 'মিরপুর']],
    'Magura' => [['en' => 'Magura Sadar', 'bn' => 'মাগুরা সদর'], ['en' => 'Mohammadpur', 'bn' => 'মোহাম্মদপুর'], ['en' => 'Shalikha', 'bn' => 'শালিখা'], ['en' => 'Sreepur', 'bn' => 'শ্রীপুর']],
    'Meherpur' => [['en' => 'Meherpur Sadar', 'bn' => 'মেহেরপুর সদর'], ['en' => 'Gangni', 'bn' => 'গাংনী'], ['en' => 'Mujibnagar', 'bn' => 'মুজিবনগর']],
    'Narail' => [['en' => 'Narail Sadar', 'bn' => 'নড়াইল সদর'], ['en' => 'Kalia', 'bn' => 'কালিয়া'], ['en' => 'Lohagara', 'bn' => 'লোহাগড়া']],
    'Satkhira' => [['en' => 'Satkhira Sadar', 'bn' => 'সাতক্ষীরা সদর'], ['en' => 'Assasuni', 'bn' => 'আশাশুনি'], ['en' => 'Debhata', 'bn' => 'দেবহাটা'], ['en' => 'Kalaroa', 'bn' => 'কলারোয়া'], ['en' => 'Kaliganj', 'bn' => 'কালীগঞ্জ'], ['en' => 'Shyamnagar', 'bn' => 'শ্যামনগর'], ['en' => 'Tala', 'bn' => 'তালা']],
    'Jamalpur' => [['en' => 'Jamalpur Sadar', 'bn' => 'জামালপুর সদর'], ['en' => 'Baksiganj', 'bn' => 'বকশীগঞ্জ'], ['en' => 'Dewanganj', 'bn' => 'দেওয়ানগঞ্জ'], ['en' => 'Islampur', 'bn' => 'ইসলামপুর'], ['en' => 'Madarganj', 'bn' => 'মাদারগঞ্জ'], ['en' => 'Melandaha', 'bn' => 'মেলান্দহ'], ['en' => 'Sarishabari', 'bn' => 'সরিষাবাড়ী']],
    'Netrokona' => [['en' => 'Netrokona Sadar', 'bn' => 'নেত্রকোণা সদর'], ['en' => 'Atpara', 'bn' => 'আটপাড়া'], ['en' => 'Barhatta', 'bn' => 'বরহাট্টা'], ['en' => 'Durgapur', 'bn' => 'দুর্গাপুর'], ['en' => 'Khaliajuri', 'bn' => 'খালিয়াজুরী'], ['en' => 'Kalmakanda', 'bn' => 'কলমাকান্দা'], ['en' => 'Kendua', 'bn' => 'কেন্দুয়া'], ['en' => 'Madan', 'bn' => 'মদন'], ['en' => 'Mohanganj', 'bn' => 'মোহনগঞ্জ'], ['en' => 'Purbadhala', 'bn' => 'পূর্বধলা']],
    'Sherpur' => [['en' => 'Sherpur Sadar', 'bn' => 'শেরপুর সদর'], ['en' => 'Jhenaigati', 'bn' => 'ঝিনাইগাতী'], ['en' => 'Nakla', 'bn' => 'নাকলা'], ['en' => 'Nalitabari', 'bn' => 'নালিতাবাড়ী'], ['en' => 'Sreebardi', 'bn' => 'শ্রীবরদী']],
    'Joypurhat' => [['en' => 'Joypurhat Sadar', 'bn' => 'জয়পুরহাট সদর'], ['en' => 'Akkelpur', 'bn' => 'আক্কেলপুর'], ['en' => 'Kalai', 'bn' => 'কালাই'], ['en' => 'Khetlal', 'bn' => 'খেতলাল'], ['en' => 'Panchbibi', 'bn' => 'পাঁচবিবি']],
    'Naogaon' => [['en' => 'Naogaon Sadar', 'bn' => 'নওগাঁ সদর'], ['en' => 'Atrai', 'bn' => 'আত্রাই'], ['en' => 'Badalgachhi', 'bn' => 'বদলগাছী'], ['en' => 'Dhamoirhat', 'bn' => 'ধামইরহাট'], ['en' => 'Manda', 'bn' => 'মন্দা'], ['en' => 'Mohadevpur', 'bn' => 'মহাদেবপুর'], ['en' => 'Niamatpur', 'bn' => 'নিয়ামতপুর'], ['en' => 'Patnitala', 'bn' => 'পত্নীতলা'], ['en' => 'Porsha', 'bn' => 'পোরশা'], ['en' => 'Raninagar', 'bn' => 'রাণীনগর'], ['en' => 'Sapahar', 'bn' => 'সাপাহার']],
    'Natore' => [['en' => 'Natore Sadar', 'bn' => 'নাটোর সদর'], ['en' => 'Bagatipara', 'bn' => 'বাগাতিপাড়া'], ['en' => 'Baraigram', 'bn' => 'বড়াইগ্রাম'], ['en' => 'Gurudaspur', 'bn' => 'গুরুদাসপুর'], ['en' => 'Lalpur', 'bn' => 'লালপুর'], ['en' => 'Naldanga', 'bn' => 'নলডাঙ্গা'], ['en' => 'Singra', 'bn' => 'সিংড়া']],
    'Chapainawabganj' => [['en' => 'Chapainawabganj Sadar', 'bn' => 'চাঁপাইনবাবগঞ্জ সদর'], ['en' => 'Bholahat', 'bn' => 'ভোলাহাট'], ['en' => 'Gomastapur', 'bn' => 'গোমস্তাপুর'], ['en' => 'Nachole', 'bn' => 'নাচোল'], ['en' => 'Shibganj', 'bn' => 'শিবগঞ্জ']],
    'Pabna' => [['en' => 'Pabna Sadar', 'bn' => 'পাবনা সদর'], ['en' => 'Atgharia', 'bn' => 'আটঘরিয়া'], ['en' => 'Bera', 'bn' => 'বেড়া'], ['en' => 'Bhangura', 'bn' => 'ভাঙ্গুড়া'], ['en' => 'Chatmohar', 'bn' => 'চাটমোহর'], ['en' => 'Faridpur', 'bn' => 'ফরিদপুর'], ['en' => 'Ishwardi', 'bn' => 'ঈশ্বরদী'], ['en' => 'Santhia', 'bn' => 'সাঁথিয়া'], ['en' => 'Sujanagar', 'bn' => 'সুজানগর']],
    'Sirajganj' => [['en' => 'Sirajganj Sadar', 'bn' => 'সিরাজগঞ্জ সদর'], ['en' => 'Belkuchi', 'bn' => 'বেলকুচি'], ['en' => 'Chauhali', 'bn' => 'চৌহালি'], ['en' => 'Kamarkhanda', 'bn' => 'কামারখান্দা'], ['en' => 'Kazipur', 'bn' => 'কাজীপুর'], ['en' => 'Raiganj', 'bn' => 'রায়গঞ্জ'], ['en' => 'Shahjadpur', 'bn' => 'শাহজাদপুর'], ['en' => 'Tarash', 'bn' => 'তারাশ'], ['en' => 'Ullahpara', 'bn' => 'উল্লাপাড়া']],
    'Gaibandha' => [['en' => 'Gaibandha Sadar', 'bn' => 'গাইবান্ধা সদর'], ['en' => 'Phulchhari', 'bn' => 'ফুলছড়ি'], ['en' => 'Gobindaganj', 'bn' => 'গোবিন্দগঞ্জ'], ['en' => 'Palashbari', 'bn' => 'পলাশবাড়ী'], ['en' => 'Sadullapur', 'bn' => 'সাদুল্লাপুর'], ['en' => 'Sughatta', 'bn' => 'সাঘাটা'], ['en' => 'Sundarganj', 'bn' => 'সুন্দরগঞ্জ']],
    'Kurigram' => [['en' => 'Kurigram Sadar', 'bn' => 'কুড়িগ্রাম সদর'], ['en' => 'Bhurungamari', 'bn' => 'ভুরুঙ্গামারী'], ['en' => 'Char Rajibpur', 'bn' => 'চর রাজিবপুর'], ['en' => 'Chilmari', 'bn' => 'চিলমারী'], ['en' => 'Phulbari', 'bn' => 'ফুলবাড়ী'], ['en' => 'Nageshwari', 'bn' => 'নাগেশ্বরী'], ['en' => 'Rajarhat', 'bn' => 'রাজারহাট'], ['en' => 'Raomari', 'bn' => 'রৌমারী'], ['en' => 'Ulipur', 'bn' => 'উলিপুর']],
    'Lalmonirhat' => [['en' => 'Lalmonirhat Sadar', 'bn' => 'লালমনিরহাট সদর'], ['en' => 'Aditmari', 'bn' => 'আদিতমারী'], ['en' => 'Hatibandha', 'bn' => 'হাতিবান্ধা'], ['en' => 'Kaliganj', 'bn' => 'কালীগঞ্জ'], ['en' => 'Patgram', 'bn' => 'পাটগ্রাম']],
    'Nilphamari' => [['en' => 'Nilphamari Sadar', 'bn' => 'নীলফামারী সদর'], ['en' => 'Dimla', 'bn' => 'ডিমলা'], ['en' => 'Domar', 'bn' => 'ডোমার'], ['en' => 'Jaldhaka', 'bn' => 'জলঢাকা'], ['en' => 'Kishoreganj', 'bn' => 'কিশোরগঞ্জ'], ['en' => 'Saidpur', 'bn' => 'সৈয়দপুর']],
    'Panchagarh' => [['en' => 'Panchagarh Sadar', 'bn' => 'পঞ্চগড় সদর'], ['en' => 'Atwari', 'bn' => 'আটোয়ারী'], ['en' => 'Boda', 'bn' => 'বোদা'], ['en' => 'Debiganj', 'bn' => 'দেবীগঞ্জ'], ['en' => 'Tetulia', 'bn' => 'তেতুলিয়া']],
    'Thakurgaon' => [['en' => 'Thakurgaon Sadar', 'bn' => 'ঠাকুরগাঁও সদর'], ['en' => 'Baliadangi', 'bn' => 'বালিয়াডাঙ্গী'], ['en' => 'Haripur', 'bn' => 'হরিপুর'], ['en' => 'Pirganj', 'bn' => 'পীরগঞ্জ'], ['en' => 'Ranisankail', 'bn' => 'রাণীসংকাইল']],
    'Habiganj' => [['en' => 'Habiganj Sadar', 'bn' => 'হবিগঞ্জ সদর'], ['en' => 'Ajmiriganj', 'bn' => 'আজমিরীগঞ্জ'], ['en' => 'Baniachong', 'bn' => 'বানিয়াচং'], ['en' => 'Bahubal', 'bn' => 'বাহুবল'], ['en' => 'Chunarughat', 'bn' => 'চুনারুঘাট'], ['en' => 'Lakhai', 'bn' => 'লাখাই'], ['en' => 'Madhabpur', 'bn' => 'মাধবপুর'], ['en' => 'Nabiganj', 'bn' => 'নবীগঞ্জ']],
    'Moulvibazar' => [['en' => 'Moulvibazar Sadar', 'bn' => 'মৌলভীবাজার সদর'], ['en' => 'Barlekha', 'bn' => 'বড়লেখা'], ['en' => 'Juri', 'bn' => 'জুড়ী'], ['en' => 'Kamalganj', 'bn' => 'কমলগঞ্জ'], ['en' => 'Kulaura', 'bn' => 'কুলাউড়া'], ['en' => 'Rajnagar', 'bn' => 'রাজনগর'], ['en' => 'Sreemangal', 'bn' => 'শ্রীমঙ্গল']],
    'Sunamganj' => [['en' => 'Sunamganj Sadar', 'bn' => 'সুনামগঞ্জ সদর'], ['en' => 'Bishwamvarpur', 'bn' => 'বিশ্বম্ভরপুর'], ['en' => 'Chhatak', 'bn' => 'ছাতক'], ['en' => 'Derai', 'bn' => 'দিরাই'], ['en' => 'Dharamapasha', 'bn' => 'ধর্মপাশা'], ['en' => 'Dowarabazar', 'bn' => 'দোয়ারাবাজার'], ['en' => 'Jagannathpur', 'bn' => 'জগন্নাথপুর'], ['en' => 'Jamalganj', 'bn' => 'জামালগঞ্জ'], ['en' => 'Madhyanagar', 'bn' => 'মধ্যনগর'], ['en' => 'Shantiganj', 'bn' => 'শান্তিগঞ্জ'], ['en' => 'Tahirpur', 'bn' => 'তাহিরপুর']],
];
