@extends('admin.layouts.app')
@section('panel')
<div class="row mb-none-30">
    <div class="col-12">
        {{-- Top: Clear cache + short info --}}
        <div class="card mb-3">
            <div class="card-body py-3">
                <div class="d-flex flex-wrap gap-2 align-items-center justify-content-between">
                    <a href="{{ route('admin.system.optimize') }}" class="btn btn-outline--primary btn-sm"><i class="las la-broom me-1"></i>@lang('Clear Cache')</a>
                    <small class="text-muted">@lang('Clear cache after saving to see changes on frontend.')</small>
                </div>
            </div>
        </div>

        {{-- Sitemap & Robots – what they are and why (clean card) --}}
        <div class="card mb-4 border-success">
            <div class="card-header bg-success bg-opacity-10 border-success">
                <h5 class="mb-0 text-success"><i class="las la-sitemap me-2"></i>@lang('Sitemap & Robots')</h5>
            </div>
            <div class="card-body">
                <p class="mb-3 small text-muted">
                    @lang('These two links are automatically generated by your site. You do not need to change them when you add your domain — they will work the same way on your live domain.')
                </p>
                <ul class="mb-3 small">
                    <li><strong>@lang('Sitemap')</strong> (sitemap.xml): @lang('A list of your site’s important URLs (home, products, categories, etc.) that search engines like Google and Bing use to discover and index your pages faster. Submitting this URL in Google Search Console and Bing Webmaster helps your site rank better.')</li>
                    <li><strong>@lang('Robots')</strong> (robots.txt): @lang('Tells search engines which parts of your site they may crawl and where your sitemap is. It keeps admin and user areas private while allowing product and public pages to be indexed.')</li>
                </ul>
                <p class="mb-2 small text-muted">
                    @lang('When you use a domain (e.g. yourstore.com), the links will automatically become:')<br>
                    <code>https://yourstore.com/sitemap.xml</code> @lang('and') <code>https://yourstore.com/robots.txt</code>
                </p>
                <div class="d-flex flex-wrap gap-3 mt-3">
                    <a href="{{ url('sitemap.xml') }}" target="_blank" rel="noopener" class="btn btn-sm btn-outline-success">@lang('Open Sitemap')</a>
                    <a href="{{ url('robots.txt') }}" target="_blank" rel="noopener" class="btn btn-sm btn-outline-success">@lang('Open Robots')</a>
                </div>
            </div>
        </div>

        {{-- About SEO (compact) --}}
        <div class="alert alert-info py-2 mb-4">
            <small>@lang('These settings control default meta tags for search results and social sharing. When you deploy to your domain, update the values here — no extra setup needed.')</small>
        </div>

        <form action="{{ route('admin.frontend.sections.content', 'seo') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="type" value="data">
            <input type="hidden" name="seo_image" value="1">

            {{-- General Meta – single card, clean grid --}}
            <div class="card mb-4">
                <div class="card-header bg--primary">
                    <h5 class="text-white mb-0"><i class="las la-search me-2"></i>@lang('General Meta')</h5>
                </div>
                <div class="card-body">
                    <div class="row g-3">
                        <div class="col-xl-4">
                            <label class="form-label">@lang('Social / OG Image')</label>
                            <div class="image-upload">
                                <div class="thumb">
                                    <div class="avatar-preview">
                                        <div class="profilePicPreview" style="background-image: url({{ getImage(getFilePath('seo').'/'. @$seo->data_values->image, getFileSize('seo')) }})">
                                            <button type="button" class="remove-image"><i class="fa fa-times"></i></button>
                                        </div>
                                    </div>
                                    <div class="avatar-edit">
                                        <input type="file" class="profilePicUpload" name="image_input" id="profilePicUpload1" accept=".png,.jpg,.jpeg,.webp">
                                        <label for="profilePicUpload1" class="bg--primary">@lang('Upload Image')</label>
                                        <small class="mt-2 d-block text-muted">@lang('Supported'): <b>JPEG, PNG, WebP</b>. {{ getFileSize('seo') }}@lang('px').</small>
                                        <small class="text-muted">@lang('Recommended: 1200×630 for social sharing. WebP gives smaller file size.')</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-8">
                            <div class="form-group mb-3">
                                <label class="form-label">@lang('Meta Keywords')</label>
                                <small class="text-muted ms-1">@lang('Separate by comma or press Enter')</small>
                                <select name="keywords[]" class="form-control select2-auto-tokenize" multiple="multiple" required>
                                    @if(@$seo->data_values->keywords)
                                        @foreach($seo->data_values->keywords as $option)
                                            <option value="{{ $option }}" selected>{{ __($option) }}</option>
                                        @endforeach
                                    @endif
                                </select>
                            </div>
                            <div class="form-group mb-3">
                                <label class="form-label">@lang('Additional Keywords')</label>
                                <textarea name="additional_keywords" rows="2" class="form-control" placeholder="@lang('One per line or comma-separated. These will be merged with the keywords above.')">{{ is_array(@$seo->data_values->keywords) ? '' : '' }}</textarea>
                                <small class="text-muted">@lang('Add more keywords in bulk for advanced SEO (long-tail, local, product names).')</small>
                            </div>
                            <div class="form-group">
                                <label class="form-label">@lang('Meta Description')</label>
                                <textarea name="description" rows="3" class="form-control char-counter" data-max="160" required>{{ @$seo->data_values->description }}</textarea>
                                <small class="text-muted"><span class="char-count">0</span>/160 @lang('chars')</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {{-- Social / Open Graph --}}
            <div class="card mb-4">
                <div class="card-header"><h5 class="mb-0"><i class="lab la-facebook-f me-2"></i>@lang('Social / Open Graph')</h5></div>
                <div class="card-body">
                    <div class="row g-3">
                        <div class="col-md-6">
                            <label class="form-label">@lang('Social Title')</label>
                            <input type="text" class="form-control char-counter" name="social_title" value="{{ @$seo->data_values->social_title }}" data-max="60" required maxlength="70"/>
                            <small class="text-muted"><span class="char-count">0</span>/60</small>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">@lang('Social Description')</label>
                            <textarea name="social_description" rows="2" class="form-control char-counter" data-max="160" required>{{ @$seo->data_values->social_description }}</textarea>
                            <small class="text-muted"><span class="char-count">0</span>/160</small>
                        </div>
                    </div>
                </div>
            </div>

            {{-- One row: Canonical, Verification, Twitter, OG --}}
            <div class="card mb-4">
                <div class="card-header"><h5 class="mb-0"><i class="las la-cog me-2"></i>@lang('URLs, Verification & Social')</h5></div>
                <div class="card-body">
                    <div class="row g-3">
                        <div class="col-12">
                            <label class="form-label">@lang('Canonical Base URL')</label>
                            <input type="url" class="form-control" name="canonical_base" value="{{ @$seo->data_values->canonical_base }}" placeholder="{{ url('/') }}"/>
                            <small class="text-muted">@lang('Leave empty to use current domain.')</small>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">@lang('Google Site Verification')</label>
                            <input type="text" class="form-control" name="google_site_verification" value="{{ @$seo->data_values->google_site_verification }}" placeholder="content=xxxxxxxxxx"/>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">@lang('Bing Site Verification')</label>
                            <input type="text" class="form-control" name="bing_site_verification" value="{{ @$seo->data_values->bing_site_verification }}" placeholder="xxxxxxxxxx"/>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">@lang('Twitter @username')</label>
                            <input type="text" class="form-control" name="twitter_handle" value="{{ @$seo->data_values->twitter_handle }}" placeholder="YourStore" maxlength="20"/>
                        </div>
                        <div class="col-md-3">
                            <label class="form-label">@lang('OG Site Name')</label>
                            <input type="text" class="form-control" name="og_site_name" value="{{ @$seo->data_values->og_site_name }}" placeholder="{{ isset($general) && $general ? ($general->sitename ?? '') : 'My Store' }}" maxlength="80"/>
                        </div>
                        <div class="col-md-3">
                            <label class="form-label">@lang('OG Locale')</label>
                            <input type="text" class="form-control" name="og_locale" value="{{ @$seo->data_values->og_locale ?? 'en_GB' }}" placeholder="en_GB" maxlength="10"/>
                        </div>
                    </div>
                </div>
            </div>

            {{-- Advanced: Robots + JSON-LD --}}
            <div class="card mb-4">
                <div class="card-header"><h5 class="mb-0"><i class="las la-sliders-h me-2"></i>@lang('Advanced')</h5></div>
                <div class="card-body">
                    <div class="row g-3">
                        <div class="col-md-6">
                            <label class="form-label">@lang('Meta Robots')</label>
                            <select class="form-control" name="robots">
                                <option value="index, follow" {{ (@$seo->data_values->robots ?? 'index, follow') == 'index, follow' ? 'selected' : '' }}>index, follow</option>
                                <option value="noindex, follow" {{ (@$seo->data_values->robots ?? '') == 'noindex, follow' ? 'selected' : '' }}>noindex, follow</option>
                                <option value="index, nofollow" {{ (@$seo->data_values->robots ?? '') == 'index, nofollow' ? 'selected' : '' }}>index, nofollow</option>
                                <option value="noindex, nofollow" {{ (@$seo->data_values->robots ?? '') == 'noindex, nofollow' ? 'selected' : '' }}>noindex, nofollow</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">@lang('JSON-LD Organization')</label>
                            <select class="form-control" name="jsonld_organization">
                                <option value="1" {{ (int)(@$seo->data_values->jsonld_organization ?? 1) === 1 ? 'selected' : '' }}>@lang('Enable')</option>
                                <option value="0" {{ (int)(@$seo->data_values->jsonld_organization ?? 1) === 0 ? 'selected' : '' }}>@lang('Disable')</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>

            {{-- Tips (collapsed style) --}}
            <div class="card mb-4 border-primary border-opacity-25">
                <div class="card-body py-3">
                    <h6 class="text--primary mb-2"><i class="las la-lightbulb me-1"></i>@lang('Tips')</h6>
                    <ul class="mb-0 small text-muted list-unstyled">
                        <li>@lang('Meta description: 150–160 chars')</li>
                        <li>@lang('Title: 50–60 chars')</li>
                        <li>@lang('Social image: 1200×630; WebP supported')</li>
                        <li>@lang('Submit sitemap in Search Console')</li>
                    </ul>
                </div>
            </div>

            <div class="card">
                <div class="card-body py-3">
                    <button type="submit" class="btn btn--primary btn-lg w-100"><i class="las la-save me-2"></i>@lang('Save SEO Settings')</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@push('script')
<script>
(function($) {
    "use strict";
    $('.select2-auto-tokenize').select2({
        dropdownParent: $('.select2-parent'),
        tags: true,
        tokenSeparators: [',']
    });
    function updateCharCount(el) {
        var $el = $(el);
        var val = $el.val() || '';
        var max = parseInt($el.data('max')) || 160;
        var $counter = $el.closest('.form-group').find('.char-count');
        if (!$counter.length) $counter = $el.closest('.row').find('.char-count');
        $counter.text(val.length);
        $counter.toggleClass('text-danger', val.length > max);
    }
    $('.char-counter').each(function() { updateCharCount(this); });
    $('.char-counter').on('input', function() { updateCharCount(this); });
})(jQuery);
</script>
@endpush
